<?php

/**
 * Implements hook_menu().
 */
function hello_menu() {
  $items['hello'] = array(
    'title' => 'Hello Page',
    'page callback' => 'hello_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 *  Page callback for "Hello" page.
 */
function hello_page() {
  return "Hello World!";
}

/*
 * Implements hook_block_info().
 */
function hello_block_info() {
  // This example comes from node.module.
  $blocks['current_ip'] = array(
    'info' => t("Current User's IP"),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}
